---
- name: Test ansible-role-php7-phalcon
  hosts: all
  become: true

  pre_tasks:
    - name: Add repository for PHP 7
      apt_repository: repo='ppa:ondrej/php'
      tags: system

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.php
      php_packages:
        - php7.0
        - php7.0-gd
        - php7.0-curl
    - role: geerlingguy.composer
    - role: .
      php7_phalcon_php_version: "7.0"
      php7_phalcon_zephir_required_packages:
        - gcc
        - make
        - re2c
        - libpcre3-dev
        - build-essential
        - php7.0-cli
        - php7.0-gd
        - php7.0-curl
        - php7.0-intl
        - php7.0-mbstring
        - php7.0-xml
        - php7.0-dev
        - php7.0-zip
        - php7.0-fpm
      php7_phalcon_enable_cli_ini: True
      php7_phalcon_enable_fpm_ini: True
      php7_phalcon_install_devtools: True
