---
- name: Test ansible-role-php7-phalcon
  hosts: all
  become: true

  pre_tasks:
    - name: Add repository for PHP 7
      apt_repository: repo='ppa:ondrej/php'
      tags: system

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.php
      php_packages:
        - php7.1
        - php7.1-gd
        - php7.1-curl
    - role: geerlingguy.composer
    - role: .
      php7_phalcon_php_version: "7.1"
